//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id_Cita { get; set; }
        public string FechaCita { get; set; }
        public string HoraCita { get; set; }
        public Nullable<int> Id_Doctor { get; set; }
        public Nullable<int> Id_Paciente { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
